server.port: 8080

# Spring configs
spring:
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
  data:
    uri: mongodb://localhost:27017/dbUsers
rabbitmq:
  connections:
    - name: USER
      addresses: localhost:5672
      credentials:
        username: guest
        password: guest
        virtual-host: user
  bindings:
    - exchange: ha.user
      routing-key: ha.user.rk
      queue: ha.user.input


