mongodb:
  image: mongo:3.6.13
  ports:
    - "27017:27017"
  command: --smallfiles

rabbitmq:
  image: rabbitmq:3.6.16-management-alpine
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest
    RABBITMQ_DEFAULT_VHOST: user
